NotificationDotNet6/Models/ErrorViewModel.cs
namespace NotificationDotNet6.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

NotificationDotNet6/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using NotificationDotNet6.Models;

namespace NotificationDotNet6.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

NotificationDotNet6/Controllers/ModuleController.cs
using Microsoft.AspNetCore.Mvc;

namespace NotificationDotNet6.Controllers;

public class ModuleController : Controller
{
    public IActionResult Module1()
    {
        return View();
    }

    public IActionResult Module2()
    {
        return View();
    }

    public IActionResult Module3()
    {
        return View();
    }
}

NotificationDotNet6/Controllers/NotificationController.cs
using Microsoft.AspNetCore.Mvc;
using NotificationDotNet6.Domain.Commands.Notification;
using NotificationDotNet6.Domain.Entities;
using NotificationDotNet6.Domain.Services;

namespace NotificationDotNet6.Controllers;

public class NotificationController : Controller
{
    private readonly INotificationService _notificationService;

    public NotificationController(INotificationService notificationService)
    {
        _notificationService = notificationService;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var result = await _notificationService.GetAll();
        return View(result.Data as List<Notification>);
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(NotificationCreateCommand command)
    {
        var result = await _notificationService.Handle(command);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public ActionResult AllNotifications()
    {
        return View();
    }

    [HttpGet]
    public async Task<JsonResult> GetNotifications()
    {
        var request = new NotificationGetUserIdUnreadCommand { UserId = new Guid("3542838E-226D-4C34-A7F4-8E7EC3EB4A18"), Unread = false };
        var result = await _notificationService.Handle(request);

        return Json(result.Data);
    }

    [HttpGet]
    public async Task<JsonResult> GetAllNotifications()
    {
        var request = new NotificationGetUserIdUnreadCommand { UserId = new Guid("3542838E-226D-4C34-A7F4-8E7EC3EB4A18"), Unread = false };
        var result = await _notificationService.Handle(request);

        return Json(result.Data);
    }
}

NotificationDotNet6/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NotificationDotNet6.Domain.Commands.User;
using NotificationDotNet6.Domain.Entities;
using NotificationDotNet6.Domain.Services;

namespace NotificationDotNet6.Controllers;

public class UserController : Controller
{
    private readonly IUserService _userService;

    public UserController(IUserService userService)
    {
        _userService = userService;
    }

    [HttpGet]
    public async Task<IActionResult>  Index()
    {
        var result = await _userService.GetAll();
        return View(result.Data as List<User>);
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(UserCreateCommand command)
    {
        var result = await _userService.Handle(command);

        return RedirectToAction("Index");
    }
}

NotificationDotNet6/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

NotificationDotNet6/Views/Module/Module1.cshtml
@{
    ViewData["Title"] = "Module 1";
}

<h1>@ViewData["Title"]</h1>

NotificationDotNet6/Views/Module/Module2.cshtml
<h1>Module 1</h1>

NotificationDotNet6/Views/Module/Module3.cshtml
@{
    ViewData["Title"] = "Module 3";
}

<h1>@ViewData["Title"]</h1>

NotificationDotNet6/Views/Notification/AllNotifications.cshtml
@{
    ViewData["Title"] = "Notification for My";
}

<h1>@ViewData["Title"]</h1>

<table id="tblNotification" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>From</th>
            <th>Title</th>
            <th>Detail</th>
            <th>IsRead</th>
            <th>Notification Datetime</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $.ajax({
            type: 'GET',
            dataType: 'json',
            url: '/Notification/GetAllNotifications',
            traditional: true,
            contentType: 'application/json; charset=utf-8',
            success: function (data) {
                var notifications = data;
                $.map(notifications, function (notification) {
                    let tbody = `
                    <tr>
                        <td>${notification.fromUserName}</td>
                        <td>${notification.header}</td>
                        <td>${notification.body}</td>
                        <td>${notification.isReadSt}</td>
                        <td>${notification.createdDate}</td>
                    <tr>`;

                    $('#tblNotification tbody').append(tbody);
                });
            },
            error: function (xhr, status, error) {

            }
        })
    })
</script>

NotificationDotNet6/Views/Notification/Create.cshtml
@model NotificationDotNet6.Domain.Commands.Notification.NotificationCreateCommand

@{
    ViewData["Title"] = "Notification Create";
}

<h1>@ViewData["Title"]</h1>

@using (Html.BeginForm("Create", "Notification", FormMethod.Post, new { id = "frmNotificationCreate" }))
{
    <div class="modal-content">
        <div class="modal-header">
            <h3 class="modal-title">@ViewData["Title"]</h3>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Header)
                        @Html.TextBoxFor(m => m.Header, new { @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Body)
                        @Html.TextAreaFor(m => m.Body, new { @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Url)
                        @Html.TextBoxFor(m => m.Url, new { @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-6 col-sm-6 col-md-6 col-lg-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.FromUserId)
                        @Html.TextBoxFor(m => m.FromUserId, new { @class = "form-control" })
                    </div>
                </div>
                <div class="col-6 col-sm-6 col-md-6 col-lg-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.ToUserId)
                        @Html.TextBoxFor(m => m.ToUserId, new { @class = "form-control" })
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer justify-content-between">
            <a class="btn btn-danger" asp-controller="Notification" asp-action="Index">Voltar</a>
            <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
    </div>
}

NotificationDotNet6/Views/Notification/Index.cshtml
@model List<Notification>

@{
    ViewData["Title"] = "Notification";
}

<h1>@ViewData["Title"]</h1>
<a class="btn btn-success" asp-controller="Notification" asp-action="Create"> Create </a>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Header</th>
            <th>Body</th>
            <th>IsRead</th>
            <th>Url</th>
            <th>FromUserId</th>
            <th>ToUserId</th>
            <th>CreatedAt</th>
            <th>UpdatedAt</th>
            <th>Active</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var notification in Model)
        {
            <tr>
                <td>@notification.Id</td>
                <td>@notification.Header</td>
                <td>@notification.Body</td>
                <td>@notification.IsRead</td>
                <td>@notification.Url</td>
                <td>@notification.FromUserId</td>
                <td>@notification.ToUserId</td>
                <td>@notification.CreatedAt.ToString("dd/MM/yyyy HH:mm:ss")</td>
                <td>@notification.UpdatedAt?.ToString("dd/MM/yyyy HH:mm:ss")</td>
                <td>@notification.Active</td>
            </tr>
        }
    </tbody>
</table>

NotificationDotNet6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NotificationDotNet6</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NotificationDotNet6.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/notification/ikr.notification.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NotificationDotNet6</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <div id="noti_Container"></div>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Notification" asp-action="Index">Notification</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - NotificationDotNet6 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/notification/ikr.notification.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<script type="text/javascript">
    $(document).ready(function () {
        $('#noti_Container').ikrNotificationSetup();
        $.ajax({
            type: 'GET',
            dataType: 'json',
            url: '/Notification/GetNotifications',
            traditional: true,
            contentType: 'application/json; charset=utf-8',
            success: function (data) {
                var notifications = data;
                $("#noti_Container").ikrNotificationCount({
                    NotificationList: notifications,
                    NotiFromPropName: "FromUserName",
                    ListTitlePropName: "Header",
                    ListBodyPropName: "Body",
                    ControllerName: "Notification",
                    ActionName: "AllNotifications"
                });
            },
            error: function (xhr, status, error) {

            }
        })
    });
</script>

NotificationDotNet6/Views/User/Create.cshtml
@model NotificationDotNet6.Domain.Commands.User.UserCreateCommand

@{
    ViewData["Title"] = "User Create";
}

<h1>@ViewData["Title"]</h1>

@using (Html.BeginForm("Create", "User", FormMethod.Post, new { id = "frmUserCreate" }))
{
    <div class="modal-content">
        <div class="modal-header">
            <h3 class="modal-title">@ViewData["Title"]</h3>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Name)
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                    </div>
                </div>

            </div>
        </div>
        <div class="modal-footer justify-content-between">
            <button type="button" id="btn-cancel" value="cencel" class="btn btn-danger">Voltar</button>
            <button type="submit" id="btn-create" value="create" class="btn btn-primary">Salvar</button>
        </div>
    </div>
}

NotificationDotNet6/Views/User/Index.cshtml
@model List<User>

@{
    ViewData["Title"] = "User";
}

<h1>@ViewData["Title"]</h1>
<a class="btn btn-success" asp-controller="User" asp-action="Create"> Create </a>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>CreatedAt</th>
            <th>UpdatedAt</th>
            <th>Active</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.Id</td>
                <td>@user.Name</td>
                <td>@user.CreatedAt.ToString("dd/MM/yyyy HH:mm:ss")</td>
                <td>@user.UpdatedAt?.ToString("dd/MM/yyyy HH:mm:ss")</td>
                <td>@user.Active</td>
            </tr>
        }
    </tbody>
</table>